---
# tasks file for iac-ansible-roundcubemail
- name: Instalar Dependencias
  apt: name={{ item }} update_cache=yes state=present
  with_items: 
    - apache2
    - composer
    - python-mysqldb
    - file
    - wget
    - php-zip
    - git
    - php-mbstring
    - php-gd
    - php-dom
    - php-mysql

- name: Instalando Roundcubemail
  apt: name=roundcubemail update_cache=yes state=latest
...
