---
# tasks file for iac-ansible-roundcubemail
- yum:
  register: epel_installed
  name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
  state: latest

- yum: name={{item}} state=latest
  when: epel_installed|success
  register: dep_installed
  with_items:
          - httpd
          - php
          - mod_ssl
          - mailcap
          - php-gd 
          - php-intl 
          - php-ldap
          - php-mbstring 
          - php-pdo
          - php-pear-Auth-SASL 
          - php-pear-Net-Sieve
          - php-pear
          - php-pear-Net-SMTP
          - php-pear-Net-Socket
          - php-pear-Mail-Mime
          - php-pear-Net-IDNA2
          - php-pear-Net-LDAP2
          - php-pspell
          - php-xml

- yum: name=roundcubemail state=latest 
  when: dep_installed|success
  register: roundcube_installed
...

