---
# tasks file for iac-ansible-roundcubemail
- apt: 
    name: "{{ item }}" 
    update_cache: yes 
    state: present
  with_items: 
    - apache2
    - composer
    - python-mysqldb
    - file
    - wget
    - php-zip
    - git
    - php-mbstring
    - php-gd
    - php-dom
    - php-mysql
  when: (ansible_os_family == "Debian")
  register: result
  
- name: Instalando Roundcubemail
  apt: 
    name: roundcubemail 
    update_cache: yes 
    state: latest
  when: 
    - ansible_os_family == "Debian"
    - result is success
...
